// v2 atlas: loads every image listed by data/art.js (generated by tools/v2/build_art.py).
// Missing required art fails the boot loudly (the audit also checks every path).
(function () {
  "use strict";
  const root = () => window.SHARDS.ASSET_ROOT || "assets/";

  class Atlas {
    constructor() { this.images = new Map(); this.errors = []; this.ready = false; }
    paths() {
      const A = window.SHARDS.art, out = new Set();
      for (const s of Object.values(A.sheets)) out.add(s.path);
      for (const L of Object.values(A.levels)) {
        for (const l of L.layers) out.add(l.path);
        if (L.play) out.add(L.play);
        if (L.front) out.add(L.front);
        if (L.near) out.add(L.near.path);
        for (const f of L.fog || []) out.add(f.path);
      }
      for (const t of Object.values(A.tiles22 || {})) out.add(t.path);
      for (const u of Object.values(A.ui)) if (u && u.path) out.add(u.path);
      for (const p of Object.values(A.portraits)) out.add(p);
      for (const p of Object.values(A.thumbs)) out.add(p);
      return [...out];
    }
    async loadAll() {
      if (!window.SHARDS.art) throw new Error("data/art.js missing");
      const list = this.paths();
      await Promise.all(list.map((p) => this._load(p)));
      if (this.errors.length) throw new Error("ATLAS LOAD FAILED:\n" + this.errors.join("\n"));
      this.ready = true;
    }
    async loadOptional() { /* v2: everything is required */ }
    _load(path) {
      return new Promise((resolve) => {
        const img = new Image();
        img.onload = () => { this.images.set(path, img); resolve(); };
        img.onerror = () => { this.errors.push(path + ": FAILED TO LOAD"); resolve(); };
        img.src = root() + path;
      });
    }
    require(path) {
      const img = this.images.get(path);
      if (!img) throw new Error("Missing atlas image: " + path);
      return img;
    }
  }
  window.SHARDS.Atlas = Atlas;
})();
